iNav/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import patterns, include, url


from django.contrib import admin
from buildings.models import *
from django.conf import settings
from django import forms
from django.views.generic.simple import direct_to_template
import allauth


admin.autodiscover()
admin.site.register(Building)
admin.site.register(Floor)
admin.site.register(Point)
admin.site.register(Room)
admin.site.register(Path)

    
urlpatterns = patterns('',
   
        # Admin 
        url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
        url(r'^admin/', include(admin.site.urls)),
            
        # Users
        (r'^accounts/', include('allauth.urls')),

            
        # vetrina dell'applicazione (da creare)
        url(r'^buildings/iNav/$', 'buildings.views.show'),
        
        # index
        url(r'^buildings/$', 'buildings.views.index'),
        
        # visualizzazione degli edifici creati più recentemente 
        url(r'^buildings/update_list', 'buildings.views.update_list'),
        
        # recupero un edificio in base all'id, o di una lista di edifici in base alla posizione
        url(r'^buildings/get/building=(?P<id_>-?\d+)&(?P<latitude>-?\d+\.\d+)&(?P<longitude>-?\d+\.\d+)&(?P<radius>\d+)', 'buildings.views.getBuildings'), 
        
        # recupero i piani di un edificio (usato nel wizard)
        url(r'^buildings/get/floor&(?P<building_id>\d+)', 'buildings.views.getFloors'),   
        
        # cancellazione di un edificio in base all'id
        url(r'^buildings/delete=(?P<b_id>\d+)', 'buildings.views.delete'),   
        
        
        # generazione building
        url(r'^buildings/generate/new_building=(?P<idb>-?\d+)', 'buildings.views.generate_building'),
        
        
        
        
        
        
        
        
        
        
        # dettagli di un edificio e lista dei propri edifici
        url(r'^buildings/(?P<building_id>\d+)/$', 'buildings.views.detail'),
        url(r'^buildings/my_buildings', 'buildings.views.my_buildings'),
        
        
            
            
            
       
)

if settings.DEBUG:
        # static files (images, css, javascript, etc.)
        urlpatterns += patterns('',
                (
                        r'^media/(?P<path>.*)$', 
                        'django.views.static.serve', 
                        {'document_root': settings.MEDIA_ROOT}
                )
        )

iNav/buildings/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from django.contrib.gis.db import models
from sorl.thumbnail import ImageField
import datetime
import os




# generazione dell'estensione 
def generate_extension(filename):

        estensione = '.jpg'        
        posizione_punto = filename.rfind('.')
                
        if posizione_punto > 0:
                estensione = filename[posizione_punto:]
                
        return estensione
                
    
class Building(models.Model):

        # Utente creatore dell'edificio
        utente = models.ForeignKey(User);
        
        # in pratica toString()
        def __unicode__(self):
                return self.nome
         
       # creazione del percorso per il salvataggio della foto di vetrina
        def content_file_name(instance, filename):

                return '/'.join(['buildings', 
                        str(instance.utente.pk), 
                        str(instance.pk), 
                        'vetrina' + generate_extension(filename)])
       
        
        # caratteristiche dell'edificio (PUNTO 1)
        nome = models.CharField(max_length=200, unique=True)
        descrizione = models.TextField(max_length=1000, blank=True)
        link = models.URLField(blank=True)
        
        foto = ImageField(upload_to=content_file_name, blank=True)
        
        
        # Geo Django (PUNTO 2):
        posizione = models.PointField(help_text="POINT(longitude latitude)", unique=True, srid=4326, null=True, blank=True)
        geometria = models.PolygonField(help_text="POLYGON((longitude latitude, ..))", srid=4326, null=True, blank=True, geography=True)
        
        # Necessario per le geoquery
        objects = models.GeoManager() 
        
        # declinazione magnetica di base dell'edificio (rispetto al nord di google)
        base_bearing = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)
        
        # Dati sulla posizione (usati nella ricerca)
        nazione = models.CharField(max_length=30, blank=True)
        citta = models.CharField(max_length=30, blank=True)

        
        
        # dati interni dell'applicazione points
        versione = models.IntegerField() 
        data_creazione = models.DateTimeField('data creazione')
        data_update = models.DateTimeField('data update')
        
        # indica che il building è pronto per la visualizzazione
        pronto = models.BooleanField() 
        
           
        
                
class Floor(models.Model):
    
          
        # creazione del percorso per il salvataggio delle foto dei piani
        def content_file_name(instance, filename):

                nome_piano = 'floor_' + str(instance.numero_di_piano)
                
                return '/'.join(['buildings', 
                        str(instance.building.utente.pk), 
                        str(instance.building.pk), 
                        nome_piano + generate_extension(filename)])
                        
        # edificio di riferimento
        building = models.ForeignKey(Building)
        
        # dati vari del piano   
        numero_di_piano = models.IntegerField()
        immagine = ImageField(upload_to=content_file_name)
            
        # valore di discostamento dal building.base_bearing
        bearing = models.DecimalField(max_digits=9, decimal_places=6, null=True)
        
        # valori per rappresentare l'immagine del piano sulla mappa
        
        # zoom dell'immagine sulla mappa: 
        # IMPORTANTE: si riferisce ad un'immagine con larghezza di 400px!!!!!!!!!!!!!
        zoom_on_map = models.DecimalField(max_digits=6, decimal_places=3, null=True)
        # zoom della mappa
        zoom_of_map = models.IntegerField(max_length=2, null=True)
        # posizione dell'immagine
        posizione_immagine = models.PointField(help_text="POINT(longitude latitude)", null=True, srid=4326)
        




 # modificare per usare class PointField 
class Point(models.Model):

        # edificio di riferimento
        building = models.ForeignKey(Building)
        
        # piano su cui si trova il punto
        piano = models.ForeignKey(Floor)
        
        # RFID
        RFID = models.CharField(max_length=200, blank=True)
        
        # posizione dei punti sull'immagine
        x = models.IntegerField()
        y = models.IntegerField()
        
        # valore booleano che indica se quello è un ingresso
        ingresso = models.BooleanField()
       
          
    
class Room(models.Model):
            
        # edificio di riferimento
        building = models.ForeignKey(Building)
        
        # punto di riferimento
        punto = models.OneToOneField(Point)
            
        # altri parametri descrittivi
        nome_stanza = models.CharField(max_length=200, blank=True)
        persone = models.CharField(max_length=200, blank=True)
        altro = models.CharField(max_length=200, blank=True)
        link = models.URLField(blank=True)
            
        def __unicode__(self):
                return self.nome_stanza    
    
# modificare con class MultiLineStringField per contenere tutte le path di un piano in un solo oggetto
class Path(models.Model):

        # edificio di riferimento
        building = models.ForeignKey(Building)
        
        # punto di partenza
        a = models.ForeignKey(Point, related_name='path_A')
        
        # punto di arrivo
        b = models.ForeignKey(Point, related_name='path_B')
        
        # valori di ascensore/scala, usati per dare migliori indicazioni e 
        # aiutare la computazione dei percorsi (vengono usati anche come indicatori booleani)
        ascensore  = models.CharField(max_length=50, blank=True)
        scala  = models.CharField(max_length=50, blank=True)
        
  
# personalizzazione del User di default di django
from django.db.models.signals import *
        
class UserAdditionalFields(models.Model):

        user = models.OneToOneField(User)
        
        # valore che indica il numero di edifici incompleti per ogni utente 
        incomplete_buildings = models.IntegerField(null=False, default=0)
        
        # valore che indica gli edifici creati da ogni utente
        complete_buildings = models.IntegerField(null=False, default=0)
       
         # necessario per il salvataggio dell'utente
        def create_user_profile(sender, instance, created, **kwargs):
                if created:
                        UserAdditionalFields.objects.create(user=instance)
                        
        # aggiungere controllo per creazione e cancellazione edificio                
        
        post_save.connect(create_user_profile, sender=User)
        
    

templates/buildings/generate4/generate-index.html
{% extends "base.html" %}

{% block imports %} 
        
        
        <script type="text/javascript"
        src="http://maps.googleapis.com/maps/api/js?key=AIzaSyA6Cod-waBAQwWkS-vEsAIST3x2HtgsaNg&sensor=false&libraries=geometry">
        </script>
        <script type="text/javascript"
        src="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/infobubble/src/infobubble.js">
        </script>

        <script type="text/javascript"
        src="{{STATIC_URL}}java/jquery-1.8.2.js">
        </script>
        
        <script type="text/javascript" 
       src="{{STATIC_URL}}java/map.index.js"> 
       </script>
       
       <script type="text/javascript" 
       src="{{STATIC_URL}}java/map.geocoding.js"> 
       </script>
       
       <script type="text/javascript" 
       src="{{STATIC_URL}}java/map.generatePolygon.js"> 
       </script>
       <script type="text/javascript"
        src="{{STATIC_URL}}java/richmarker.js">
        </script>
        
<script type="text/javascript">

// VARIABILI /////////////////////////////////////////////////////////////////////////


// contiene tutti i poligoni che saranno disegnati sulla mappa, compreso quello creato dall'utente
var polygons = new google.maps.MVCArray();

// mappa
var map;

// larghezza della mappa (in pixels)
//var width = 0;

var id = -1;

var bounds = null;

// booleano per stabilire se l'edificio è già stato disegnato oppure no

var disegnato = false;
var ready = false;


// chiamata al loading della pagina
function initialize() {
        
        id = {{ request.user.id }}
        
        // carico la mappa
        loadMap();

        // qui carico i poligoni di tutti i buildings        
        loadAllPolygons();
        
        // inizializzo le variabili globali del js
        initializeJS(map, polygons);
        
        {% if building.geometria %}
                
                // genero il poligono dell'utente
                polygons = parseJSONPolyline({{building.geometria.geojson|safe}}, id, polygons, map);
                setUserPolygonReady();
                
                disegnato = true;
                ready = true;
        
        {% else %}
        
                // abilito il disegno dell'edificio da parte dell'utente
                polygons = disegna_edificio(polygons, id); 
                
                disegnato = false;
                ready = true;
        
        {% endif %}
                 
}

// passo il valore "disegnato" 
function getDisegnato() {
        return disegnato;
}

function setDisegnato(value) {
        disegnato = value;
}

function getReady() {
        return ready;
}

function getBounds() {
        return bounds;
}

// Caricamento della mappa
function loadMap() {

        mapOptions = {
                center: new google.maps.LatLng(-0, 0),
                zoom: 1,
                mapTypeId: google.maps.MapTypeId.HYBRID
        };
        
        map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
        
}

// caricamento dei poligoni
function loadAllPolygons() {

        {% for b in buildings %}
                polygons = parseJSONPolyline({{b.geometria.geojson|safe}}, {{b.utente.id}}, polygons, map);
        {% endfor %}
}

var test = false;
// funzione (chiamata anche dall'iframe) per convertire il poligono dell'utente, centrarlo e
// disabilitarne il disegno
function setUserPolygonReady() {
               
              
                // converto il poligono generico (appena creato) in quello dell'utente
                polygons = convertPolygonToNewBuildingPolygon(polygons, id);
                
                // imposto lo zoom e la posizione ottimali per visualizzare il poligono
                bounds = setOptimalPanEZoom(polygons.getAt(polygons.length - 1));
                
                // blocco la possibilità di disegnare altri edifici
                bloccaDisegno();
        
                // imposto la larghezza (in pixel) della mappa
               // width = transformBuondsToPixels(bounds);
                
              //  google.maps.event.addListener(map, 'idle', function() {
                        
                document.getElementById('the_iframe').contentWindow.setBounds(bounds);
                               // window.frames['iframe'].setBounds(bounds);
                document.getElementById('the_iframe').contentWindow.setMap(map);
                
                google.maps.event.addListener(map, 'idle', function() {
                        try {
                                document.getElementById('the_iframe').contentWindow.setRadioButtonsEnabled(); 
                        } catch (e) {
                                google.maps.event.clearListeners(map, 'idle');
                        }
                                              
                });  
        
           //     });
           
}

// funzione usata per resettare l'altezza dell'iframe tra una pagina e l'altra
function setHeight(value) {
        document.getElementById('the_iframe').height= (value) + "px";
}


</script>
{%endblock imports %}




{% block body %}

<body onload="initialize()">
  
    <input id="address" input type="text" style="color:#888;" 
    value="Write an address here!" onfocus="inputFocus(this)" onblur="inputBlur(this)" />
      <input type="button" value="Find!" onclick="codeAddress()">
      
    <div id="map_canvas"></div>

</body>
{% endblock body %}


{% block extra_body %}          



<iframe width="100%" id="the_iframe" name="iframe" onLoad="calcHeight();" src="{% url buildings.views.step new_id=building.pk %}"  height="1"> An iframe capable browser is required to view this web site. </iframe>

<!-- seamless="seamless" scrolling="NO" frameborder="0" -->
   
{% endblock extra_body %} 

templates/buildings/generate4/generate-map.html
{% extends "base.html" %}


{% block body %}
<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.1.min.js"></script>
        
<script type="text/javascript">

        var counter = {};
 
 // FUNZIONI STANDARD DELLA PAGINA /////////////////////////////////////////////////
 
        // comunica all'iframe di fermare il refresh
        function stopRefresh() {
               return true;
        } 
 
        // questa funzione ridimensiona l'iFrame in base agli elementi mostrati
        function resizeIframe(value) {
                var new_heigth = $("#the_iframe").contents().find("body").outerHeight(true) + value;
         
                $("#the_iframe").animate(
                        {height: $("#the_iframe").contents().find("body").outerHeight(true) + value},
                                "slow","swing"
                );
        }
 ////////////////////////////////////////////////////////////////////////////////////
 
 
 // FUNZIONI PER L'INTERAZIONE CON LA JAPPLET /////////////////////////////////////
 
        // Creazione di un nuovo marker
        function createNewMarker(id, x, y, piano) {
 
                this.id = parseInt(id);
                this.x = parseInt(x);
                this.y = parseInt(y);
                this.piano = parseInt(piano)
                document.getElementById('the_iframe').contentWindow.addMarker(this.id, this.x, this.y, this.piano);
        }
 

        // aggiorno la modalità di funzionamento (marker o path)
        function updateOperationType(input) {
                console.log(input);
                mapGenerator.setOperation(input);
        }
        
        // aggiorno il piano selezionato
        function updateFloor(input) {
                mapGenerator.setFloor(input);
        }
        
        // abilito gli input per i marker e i piani
        function enableInputs() {
                document.getElementById('the_iframe').contentWindow.enableInputOptions();
        }
 
        // COMUNICO ALLA JAPPLET CHE HO CONCLUSO LE OPERAZIONI
        function operationComplete(saved, id, type, access) {
                mapGenerator.operationComplete(saved, id, type, access);
        }
        
        // Funzione chiamata dalla japplet per l'editing di un marker
        function editMarker(id) {
                document.getElementById('the_iframe').contentWindow.editMarker(parseInt(id));
        }
        
        function updatePosition(id, x, y) {
                document.getElementById('the_iframe').contentWindow.updatePosition(parseInt(id), parseInt(x), parseInt(y));
        } 
        
        // chiamata al momento della selezione di una path per proporre la sua cancellazione
        function deletePath() {
                document.getElementById('the_iframe').contentWindow.deletePath();
        }
 
        // funzione che viene chiamata ogni volta che è effettuata una validazione, per abilitare 
        // o disabilitare il pulsante "next"
        // 1 => abilita
        // 0 => disabilita
        function isValid(value) {
                document.getElementById('the_iframe').contentWindow.enableNext(parseInt(value));
        }
        
        
        // funzione per il recupero delle path e il parsing dell'output dell'Applet
        // #numero_di_piano;P.marker.id,P.x,P.y,A.marker.id,A.x,A.y; ... ## ... # ..
        function getPaths() {
                var temp_paths = mapGenerator.getPaths();
                var out = {};

                // divido i vari gruppi di array
                var array_list = temp_paths.split("#");
              
                for (var al in array_list) {
                
                        if (array_list[al].length > 0) {
                                
                                // separo i singoli oggetti
                                var objects = array_list[al].split(";");
                                
                                var numero_di_piano = parseInt(objects[0]);
                                var array = [];
                                for (var o in objects) {
                                        if ((objects[o].length > 0) && (o > 0)) {
                                                // estrapolo le coordinate
                                                var coordinates = objects[o].split(",");
                                                var path = []
                                                for (var i=0; i < 6; i++) 
                                                        path[i] = parseInt(coordinates[i]);
                                                
                                                // salvo le coodinate della path nell'array del piano
                                                array.push(path);
                                        }                                
                                } 
                                
                                // salvo l'array delle path del piano nel dizionario
                                out[numero_di_piano] = array;                        
                        }              
                }
                return out;        
        }
        
        
        
        // funzione per caricare i piani nelle options dell'iframe
        function sendFloorsToIframe(json) {
                var floors = [];
                
                for (var j in json) 
                        floors[floors.length] = parseInt(json[j].numero_di_piano);
                try {
                        document.getElementById('the_iframe').contentWindow.addFloor(floors);
                } catch (err) {
                        setTimeout(function() {sendFloorsToIframe(json); },500);
                }
        }
 
        
 
 
//////////////////////////////////////////////////////////////////////////////////////////////
  
  
  
  
  
       
  
 
 
</script>


<applet name="mapGenerator"
        id="mapGenerator"  
        code="main.MapGenerator.class"
        archive="{{STATIC_URL}}jar/MapGenerator.jar">
        <param name="MAYSCRIPT" value="true">             
</applet>
  

{% endblock body %}

{% block extra_body %}

<iframe width="100%" id="the_iframe" name="iframe" onLoad="calcHeight();" src="{% url buildings.views.step new_id=building.pk %}"  height="1" > An iframe capable browser is required to view this web site. </iframe>

{% endblock extra_body %}

templates/buildings/generate4/point.html
<form enctype="multipart/form-data" action="point.html" method="post">
        {% csrf_token %}
        
        {{form}}
        
<input type="submit" value="Save" />

templates/buildings/generate4/redirect.html
<body onload="window.top.location='{% url buildings.views.detail building_id=building.id %}'">

templates/buildings/generate4/step0.html
{% extends "generate_building.html" %} 

{% block functions %}

<script type="text/javascript">

// funzione per il bottone di incremento/decremento del numero di piani
$(function() {

    $(".button").parent().find("input").prop('readonly', "readonly");
    $(".button").click(function() {
        var $button = $(this);
        var oldValue = $button.parent().find("input").val();
    
        if ($button.text() == "+") 
    	  var newVal = parseFloat(oldValue) + 1;
    	else {

    	  if (oldValue > 1) 
    	      var newVal = parseFloat(oldValue) - 1;
    	  else
    	        var newVal = 1;
    	}
    	$button.parent().find("input").val(newVal);
    });

});

function resetHeight() {
        window.top.setHeight(0);
}

</script>  

{% endblock functions %}


{% block body %}

<body>

<p> Hello!</p>
<p>Thank you for start creating a new building!!!</p>
<p>First of all, you have to draw the shape of your building on the map on the left.
Here are the instructions:</p> 
        <ul>
        <li>If you click on the map you create a new Marker.</li> 
        <li>If you click on a Marker, you can move or delete it.</li>
        <li>Be careful and accurate!</li>
        </ul>
        
<p> Down here you can tell us some additional details about your building.</p> 

<form enctype="multipart/form-data" action="{% url buildings.views.step new_id=building.pk %}" method="post">{% csrf_token %}
        {{ form.non_field_errors }}
    <div class="fieldWrapper">
        {{ form.nome.errors }}
        {{ form.geometria.errors }}
        
        <label for="id_nome">Name*:</label></br>
        {{ form.nome }}
    </div> </br>
    
    <div class="fieldWrapper">
        {{ form.descrizione.errors }}
        
        <label for="id_nome">Descrizione:</label></br>
        {{ form.descrizione }}
    </div> </br>
    
    <div class="fieldWrapper" style="cols:20;">
        {{ form.link.errors }}
        
        <label for="id_nome">Link:</label></br>
        {{ form.link }}
    </div> </br>
    
    <div class="fieldWrapper" id="numero_di_piani">
        {{ form.numero_di_piani.errors }}
        <label for="id_numero_di_piani">Number of floors*:</label></br>
        <div id="input_numero_di_piani">
                {{ form.numero_di_piani }}
                <div class="inc button" 
                style="background: url({{STATIC_URL}}images/buttons.png) 
                        no-repeat; 
                        background-position: 0 -29px;">-</div>
                <div class="dec button"
                style="background: url({{STATIC_URL}}images/buttons.png) 
                        no-repeat;">+</div>
        </div>
    </div></br>
    <div class="fieldWrapper">
        {{ form.foto.errors }}
        <label for="id_foto">Insert a photo (optional):</label></br>
        {{ form.foto }}
    </div></br>
    <div class="fieldWrapper">
    {{ form.geometria }}
    </div>
    <div class="fieldWrapper">
    {{ form.posizione }}
    </div>
    <p><input type="submit" value="Next" onclick="resetHeight()"/></p>
</form>

{%endblock body %}

templates/buildings/generate4/step1.html
{% extends "generate_building.html" %}   

{% block body %}
 
<script type="text/javascript">

// funzione per gestire l'incremento del campo "Numero di piani"



$(function() {
   
    $(".button").parent().find("input").prop('readonly', "readonly");
    $(".button").parent().find("input").val(0);
    $(".button").click(function() {
        var $button = $(this);
        var oldValue = $button.parent().find("input").val();
    
        if ($button.text() == "+") 
    	  var newVal = parseFloat(oldValue) + 1;
    	else 
    	  var newVal = parseFloat(oldValue) - 1;
    	      
    	$button.parent().find("input").val(newVal);
    	arrangeFloors();
    });
    
    
});

$(document).ready(function() {
        arrangeFloors();
});
// faccio in modo che il numero dei piani sia sempre "crescente" e che NON ci siano
// sovrapposizioni di numeri
function arrangeFloors() {

        number_of_forms = $("#id_form-TOTAL_FORMS").val();
        
        var value = NaN;
        text_a = "id_form-";
        text_b = "-numero_di_piano";
        
        for(var i=0; i < number_of_forms; i++) {
                name = '#' + text_a + i + text_b;
                
                if (value == NaN)
                        value = parseFloat($(name).val());
                else {
                        var new_value = parseFloat($(name).val());
                        if (value >= new_value) { 
                                new_value = value + 1; 
                                $(name).val(new_value);
                        }
                        value = new_value;
                }
        }
}


</script>





<form enctype="multipart/form-data" action="{% url buildings.views.step new_id=building.pk %}" method="post">
        {% csrf_token %}

        {{ formset.management_form }}
        
        <table>
                {% for form in formset %}
        
                        {{ form.non_field_errors }}
    
                                <div class="fieldWrapper">
                                        {{ form.numero_di_piano.errors }}
        
                                        <label for="id_numero_di_piano">Floor number*:</label></br>
                                        {{ form.numero_di_piano }}
                                        <div class="inc button" 
                                                style="background: url({{STATIC_URL}}images/buttons.png) 
                                                no-repeat; background-position: 0 -29px;">-</div>
                                        <div class="dec button"
                                                style="background: url({{STATIC_URL}}images/buttons.png) 
                                                no-repeat;">+</div>
                                </div> 
                                <div class="fieldWrapper">
                                        {{ form.immagine.errors }}
        
                                        <label for="id_link">Image*:</label></br>
                                        {{ form.immagine }}
                                </div> </br>
                {% endfor %}
    </table>
        
    <p><input type="submit" value="Next" onclick="resetHeight()"/></p>
    
</form>

{% endblock body %}